development:
  secret_key_base: 22bc3da06642387d1124d6ed9da31a9817bea27d19f47b360d486f52d699b65de1277aeb64e144b819311bbd0672e7ffd8b9cc42df8042148bed18d93d49ba39
  MYSQL_ROOT_PASSWORD: password
  FACEBOOK_APP_ID: (enter the Facebook App ID of the app used for Facebook Login, without the parantheses)
  FACEBOOK_SECRET_ID: (enter the Facebook Secret Key of the app used for Facebook Login, without the parantheses)
production:
  secret_key_base: 22bc3da06642387d1124d6ed9da31a9817bea27d19f47b360d486f52d699b65de1277aeb64e144b819311bbd0672e7ffd8b9cc42df8042148bed18d93d49ba39
  MYSQL_ROOT_PASSWORD: password
  FACEBOOK_APP_ID: (enter the Facebook App ID of the app used for Facebook Login, without the parantheses)
  FACEBOOK_SECRET_ID: (enter the Facebook Secret Key of the app used for Facebook Login, without the parantheses)

